spring.application.name=productos
spring.datasource.username= postgres
spring.datasource.password= gass1post
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
server.port=8081

server.servlet.context-path=/products